# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code

name: Genrefy CI - Node Install and Build
on:
  push:
    # For testing purposes this actions runs on "github-actions" branch only when files pushed
    # After testing it must set to the branch containing the release files/version 
    branches: [ "github-actions" ]

#defaults:
#  run:
#    working-directory: genrefy

jobs:
  npm_install_and_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.1]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Debug list files in root
      run: ls

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: genrefy/package-lock.json
        #package-lock.json must be added manually because it is not present in the root folder
        
    - name: Debug list files in genrefy
      working-directory: ./genrefy
      run: ls
    
    - name: Install dependencies
      working-directory: ./genrefy
      run: npm ci
    
    # Do we want to use lint-ing?
    # Then lint should be added to the project as dependency and run on local machine to generate files and foders
    #- name: Lint
    #  run: npm run lint
    
    - name: Build project
      working-directory: ./genrefy
      run: npm run build --if-present
