# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code

name: Genrefy CI - Node Install and Build
on:
  push:
    # For testing purposes this actions runs on "github-actions" branch only when files pushed
    # After testing it must set to the branch containing the release files/version 
    branches: [ "github-actions" ]

#defaults:
#  run:
#    working-directory: genrefy

jobs:
  build_and_tests:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.12.1]
        python-version: [3.11]

    steps:
    # Setup chrome for later testing
    - uses: browser-actions/setup-chrome@v1
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: genrefy/package-lock.json
        #package-lock.json must be added manually because it is not present in the root folder
    
    - name: Install Node.js dependencies
      working-directory: ./genrefy
      run: npm ci
    
    # Do we want to use lint-ing?
    # Then lint should be added to the project as dependency and run on local machine to generate files and foders
    #- name: Lint
    #  run: npm run lint
    
    - name: Build project
      working-directory: ./genrefy
      run: npm run build --if-present
      
    # --- UI Testing ---
    
    # Install all Python dependencies  
    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install Python dependencies
      working-directory: ./genrefy_ui_tests
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install selenium
    
    # Install a browser to run ui tests
    #- name: Install latest Google Chrome browser
    #  run: |
    #    sudo apt update
    #    sudo apt --only-upgrade install google-chrome-stable
    #    google-chrome --version
      
    #- name: Start and wait for local Node.js server
    #  working-directory: ./genrefy
    #  run: npm start
    #  
    #- name: Sleep for 60 seconds
    #  run: Start-Sleep -s 60
    #  shell: powershell
    #    
    #- name: Get local IP
    #  run: ipconfig
      
    - name: Run UI Tests
      uses: BerniWittmann/background-server-action@v1
      with:
        working-directory: ./genrefy
        command: python ../genrefy_ui_tests/main.py:windows
        command-windows: python ../genrefy_ui_tests/main.py:windows
        start: npm run start
        start-windows: npm run start:windows
    
    #- name: Run Selenium UI tests
    #  working-directory: ./genrefy_ui_tests
    #  run: python main.py
      
    
    
